// <auto-generated />
namespace OptionWebsite.Migration.Records
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class norequireforchoicedate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(norequireforchoicedate));
        
        string IMigrationMetadata.Id
        {
            get { return "201510111608547_no require for choice date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
