// <auto-generated />
namespace OptionWebsite.Migration.Records
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class updatestudentnamemaxchar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatestudentnamemaxchar));
        
        string IMigrationMetadata.Id
        {
            get { return "201510111821403_update student name max char"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
