// <auto-generated />
namespace OptionWebsite.Migration.Records
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reseed2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reseed2));
        
        string IMigrationMetadata.Id
        {
            get { return "201510160631023_reseed2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
